### ISSUE TITLE
How can I get all adjacent vertexs of a vertex？

### ISSUE THREAD

**Issue by chenn1u** [DeloitteDigitalAPAC/LightOSM.jl#8]

**Comment by ThatDezKnightGuy** [comment]
Hey @chenn1u, since this uses LightGraphs and related Graph packages, you can use the LightGraphs functions of `outneightbours` and `inneighbours` to get the forward and backwards adjacent nodes of the graph parameter of the OSMGraph struct. You just need to provide something like the following:

`using LightGraphs: outneighbours, inneighbour

g::OSMGraph = OSMGraph(args..., kwargs...)

fadj = outneighbors(g.graph, g.node_to_index[node_id])
badj = inneighbors(g.graph, g.node_to_index[node_id])
`

**Comment by chenn1u** [comment]
@ThatDezKnightGuy Thanks
